---
title: "Avaliable MoBI datasets"
---

This is a table of avaliable EEG datasets on [OpenNeuro](https://openneuro.org/search/modality/eeg?query=%7B%22modality_selected%22%3A%22EEG%22%7D) for the keywords specified in the table. If you find datasets missing, plesae feel free to add them here.

| OpenNeuro Accession Number | Dataset DOI                                             | Study                                                   | Tasks                                             | Authors                                                                                                      | Keywords | Mobility Tasks     | Sampling Frequency | Participants | EEG Channels | EMG Channels | IMU Tracked Points | IMU Sensor Placement         | MoCap Channels | MoCap Sensor Placement   | Misc Channel Count | Gait Events Shared | Comments                                                                                     |
|----------------------------|---------------------------------------------------------|---------------------------------------------------------|---------------------------------------------------|----------------------------------------------------------------------------------------------------------------|----------|---------------------|--------------------|--------------|--------------|--------------|---------------------|--------------------------------|---------------|--------------------------|--------------------|-------------------|---------------------------------------------------------------------------------------------|
| ds004475                   | [doi:10.18112/openneuro.ds004475.v1.0.3](https://doi.org/10.18112/openneuro.ds004475.v1.0.3) | Split-Belt Treadmill Walking                            | Treadmill Walking                                 | Noelle A. Jacobsen, Daniel P. Ferris                                                                            | gait     | Yes                 | 512                | 30           | 127          | 8            |                     |                                | 127           |                          | 1                  | Yes               | Force plates under treadmill recorded gait parameters, Dual-layer EEG setup                                    |
| ds001971                   | [doi:10.18112/openneuro.ds001971.v1.1.1](https://doi.org/10.18112/openneuro.ds001971.v1.1.1) | Audio Cue Walking Study                                 | Treadmill Walking                                 | Johanna Wagner, Ramon Martinez-Cancino, Scott Makeig, Arnaud Delorme, Christa Neuper, Teodoro Solis-Escalante, Gernot Mueller-Putz | gait     | Yes                 | 512                | 20           | 108          | 4            |                     |                                |               |                          | 1                  |                   |                                                                                             |
| ds004505                   | [doi:10.18112/openneuro.ds004505.v1.0.4](https://doi.org/10.18112/openneuro.ds004505.v1.0.4) | Table Tennis                                            | Table Tennis                                      | Amanda Studnicki, Daniel P. Ferris                                                                             | gait     | Yes                 | 250                | 25           | 120          | 8            | 20                  | Backpack, forehead, lower back | 171           |                          | 0                  |                   |                                                                                             |
| ds004033                   | [doi:10.18112/openneuro.ds004033.v1.0.0](https://doi.org/10.18112/openneuro.ds004033.v1.0.0) | Electrode Walking Study                                 | Outdoor Walking, Oddball Task, Walking Synchronization Task | Joanna Scanlon, Nadine Jacobsen, Marike Maack, Stefan Debener                                                    | gait     | Yes                 | 500                | 18           | 64           | 0            | 3                   | Right foot                     |               |                          | 1                  |                   |                                                                                             |
| ds004460                   | [doi:10.18112/openneuro.ds004460.v1.1.0](https://doi.org/10.18112/openneuro.ds004460.v1.1.0) | EEG + Motion Capture Data Set for a Full-body/Joystick Rotation Task | Rotation                                          | Gramann, K., Hohlefeld, F.U., Gehrke, L., Klug, M                                                                | gait     | Yes (Rotation)      | 1000               | 20           | 160          | 0            |                     | Both feet, hips, shoulders     | 19            |                          |                    | Unclear           |                                                                                             |
| ds003039                   | [doi:10.18112/openneuro.ds003039.v1.0.2](https://doi.org/10.18112/openneuro.ds003039.v1.0.2) | Free Walking Study                                      | Outdoor Walking                                   | Nadine Jacobsen, Sarah Blum, Karsten Witt, Stefan Debener, Joanna Scanlon                                         | walking  | Yes                 | 500                | 19           | 64           | 0            | 3                   |                                |               |                          | 1                  |                   |                                                                                             |
| ds003739                   | [doi:10.18112/openneuro.ds003739.v1.0.3](https://doi.org/10.18112/openneuro.ds003739.v1.0.3) | Perturbed Beam-Walking Task                             | Treadmill Walking                                 | Steven Peterson, Daniel Ferris                                                                                   | walking  | Yes                 | 256                | 30           | 128          | 10           | 6                   | Head, Sacrum                    | 8             |                          | 1                  |                   |                                                                                             |
| ds004625                   | [doi:10.18112/openneuro.ds004625.v1.0.2](https://doi.org/10.18112/openneuro.ds004625.v1.0.2) | Mind in Motion: Young Adults Walking Over Uneven Terrain | Walking                                           | Chang Liu, Ryan J. Downey, Jacob S. Salminen, Sofia Arvelo Rojas, Erika M. Pliner, Natalie Richer, Jungyun Hwang, Yenisel Cruz-Almeida, Todd M. Manini, Chris J. Hass, Rachael D. Seidler, David J. Clark, Daniel P. Ferris | walking  | Yes                 | 500                | 32           | 120          | 8            | 13                  | Lower Back                     |               |                          | 1                  |                   |                                                                                             |
| ds003801                   | [doi:10.18112/openneuro.ds003801.v1.0.0](https://doi.org/10.18112/openneuro.ds003801.v1.0.0) | Neural Tracking To Go                                   | Neural Tracking To Go                             | Lisa Straetmans, Bjoern Holtze, Stefan Debener, Manuela Jaeger, Bojana Mirkovic                                    | balance  | Yes                 | 250                | 20           | 24           | 0            |                     |                                |               |                          | 0                  |                   |                                                                                             |
