---
title: "EEGManySteps"
---

#  Motivation statement 
**Mobile Brain Imaging (MoBI)** is a burgeoning field enabling researchers to study brain activity in naturalistic settings. **Electroencephalography (EEG)**, a popular method for MoBI due to its portability, often faces challenges related to inconsistent experimental setups and data processing pipelines. This can hinder the reproducibility of findings.
The **EEGManySteps** initiative aims to address these issues by investigating how different experimental setups and analysis methods can influence results. By understanding the impact of acquisition and analysis protocols, we seek to enhance the consistency and reliability of EEG research in mobile environments.
We are committed to fostering Open Science by ensuring our research materials, including data sets and software, are publicly accessible and well-documented. This will enable other researchers to build upon our work, and contribute to the advancement of mobile brain imaging.

# Project
**EEGManySteps** is a community-driven initiative that arose from the direct needs of researchers. It is an inter-institute collaboration that is forming on the basis of mutual interest in the topic. The project is in its early stages and is currently being shaped by the community. The initiative is open to all researchers who are interested in contributing to the project. We are currently forming the decision-making structure of the initiative, which may change through further open discussions.

**EEGManySteps** differs from traditional replication studies by emphasizing data collection across diverse settings rather than replicating specific findings. By leveraging both preexisting datasets and newly acquired data, we seek to understand how variations in experimental setups and (pre)processing pipelines, affect the consistency and reliability of EEG results. 

The project name **"EEGManySteps"** is a reflection of the initiative's goal to explore the various steps involved in mobile EEG research. MoBI data analysis is a complex process that involves multiple stages, from data acquisition to final interpretation. By examining the impact of different choices at each step, **EEGManySteps** aims to identify influenceing factors for conducting reliable and reproducible EEG studies in mobile environments. 


# Methodology

1. **Data Sources**: We will utilize a mix of preexisting EEG datasets and new data collected from participating laboratories. 

2. **Standardization**: A protocol will be developed to assess and harmonize the data from various sources, ensuring that the collected data adheres to a common format. This protocol will facilitate the conversion of data to the [Brain Imaging Data Structure (BIDS)](https://bids-specification.readthedocs.io/en/stable/) format for [EEG](https://www.nature.com/articles/s41597-019-0104-8), [Motion](https://www.nature.com/articles/s41597-024-03559-8) and potentially EMG data.

3. **Analysis**: We invite contributions from researchers worldwide, including data, knowledge, and feedback. By fostering an inclusive and collaborative environment, we aim to build a comprehensive understanding of how different  setups and pipelines impact research findings.


# Organisation

The EEGManySteps project is lead by a [steering commitee](./team.qmd#steering-committee-members) consisting of experienced researchers from the MoBI community which will handle the day-to-day tasks and take over responsibilities in each work package. The work of the steering commitee is overseen by an [advisory board](./team.qmd#advisory-board-members) of experts from the field. Currently we drafted a proposal of 5 work packages (WPs) which take care of specific tasks.

## Workpackages (WPs)
0. Define Goals
1. Experiment protocols and data collection
2. Dissemination
3. Data curation
4. Preprocessing
5. Analysis


```{mermaid}
graph TD
    style A fill:#F0F0F0,stroke:#333,stroke-width:1px,corner-radius:5px
    style S fill:#F0F0F0,stroke:#333,stroke-width:1px,corner-radius:5px
    style B0 fill:#E8E8E8,stroke:#555,stroke-width:1px,corner-radius:5px
    style B1 fill:#E8E8E8,stroke:#555,stroke-width:1px,corner-radius:5px
    style B2 fill:#E8E8E8,stroke:#555,stroke-width:1px,corner-radius:5px
    style B3 fill:#E8E8E8,stroke:#555,stroke-width:1px,corner-radius:5px
    style B4 fill:#E8E8E8,stroke:#555,stroke-width:1px,corner-radius:5px
    style B5 fill:#E8E8E8,stroke:#555,stroke-width:1px,corner-radius:5px


    A[ Advisory Board]
    S[Steering Committee]
    B0[WP0: Define Goals]
    B1[WP1: Experiment Protocols<br>and Data Collection]
    B2[WP2: Dissemination]
    B3[WP3: Data Curation]
    B4[WP4: Preprocessing]
    B5[WP5: Analysis]

    A <--> S
    A --> B0
    S --> B0
    S --> B1
    S --> B2
    S --> B3
    S --> B4
    S --> B5

    B2 --> B3
    B3 --> B4
    B4 --> B5

    

```

## Future Directions
**Develop open-source tools**: Building upon the project's findings, EEGManySteps could contribute to the development of open-source software pipelines specifically tailored for mobile EEG data analysis. These tools would facilitate consistent processing and analysis across research laboratories, enhancing the reproducibility and comparability of MoBI studies.

**Investigate individual differences**: Future studies could explore how factors like demographics, health conditions, or individual cognitive styles impact the interpretation of MoBI data. This information would be crucial for  future research and interventions based on individual variations. By understanding how individual differences influence brain activity in mobile settings, researchers can develop more targeted and effective applications of MoBI technology.

**Create educational resources**: To promote the adoption of standardized methodologies and accelerate advancements in the field, EEGManySteps could develop educational resources and workshops to teach researchers on conducting reliable and reproducible MoBI studies. These resources could include online tutorials, hands-on training sessions, and best practices guidelines.


# Related Projects 
[ARTEM-IS](https://www.incf.org/sig/incf-working-group-artemis) : Design guidelines for evidence-based EEG methodology reporting tools.     
[EEGManyLabs](https://osf.io/yb3pq/)      : Investigating the replicability of influential EEG experiments.     
[EEGManyPipelines](https://eegmanypipelines.github.io/) : A large-scale, grassroots multi-analyst study of electroencephalography analysis practices in the wild.     
[ICMoBI](https://www.icmobi.org/)         : This is a collaborative project dedicated to identifying Independent Components of Mobile Brain Imaging.      

# Recommended Reading 
[Grasso-Cladera, A., Bremer, M., Ladouce, S., & Parada, F. (2024). A systematic review of mobile brain/body imaging studies using the P300 event-related potentials to investigate cognition beyond the laboratory. Cognitive, Affective, & Behavioral Neuroscience, 1-29.](https://link.springer.com/article/10.3758/s13415-024-01190-z)

[Richer, N., Bradford, J. C., & Ferris, D. P. (2024). Mobile neuroimaging: What we have learned about the neural control of human walking, with an emphasis on EEG-based research. Neuroscience & Biobehavioral Reviews, 105718.](https://linkinghub.elsevier.com/retrieve/pii/S0149763424001878)

[Trübutschek, D., Yang, Y. F., Gianelli, C., Cesnaite, E., Fischer, N. L., Vinding, M. C., ... & Nilsonne, G. (2024). EEGManyPipelines: A large-scale, grassroots multi-analyst study of electroencephalography analysis practices in the wild. Journal of cognitive neuroscience, 36(2), 217-224.](https://direct.mit.edu/jocn/article/36/2/217/118308/EEGManyPipelines-A-Large-scale-Grassroots-Multi)

[Niso, G., Romero, E., Moreau, J. T., Araujo, A., & Krol, L. R. (2023). Wireless EEG: A survey of systems and studies. NeuroImage, 269, 119774.](https://www.sciencedirect.com/science/article/pii/S1053811922008953)

[Niso, G., Krol, L. R., Combrisson, E., Dubarry, A. S., Elliott, M. A., François, C., ... & Chaumon, M. (2022). Good scientific practice in EEG and MEG research: Progress and perspectives. NeuroImage, 257, 119056.](https://www.sciencedirect.com/science/article/pii/S1053811922001859)

[Jacobsen, N. S. J., Blum, S., Witt, K., & Debener, S. (2021). A walk in the park? Characterizing gait‐related artifacts in mobile EEG recordings. European Journal of Neuroscience, 54(12), 8421-8440.](https://onlinelibrary.wiley.com/doi/full/10.1111/ejn.14965)

[Styles, S. J., Ković, V., Ke, H., & Šoškić, A. (2021). Towards ARTEM-IS: Design guidelines for evidence-based EEG methodology reporting tools. NeuroImage, 245, 118721.](https://www.sciencedirect.com/science/article/pii/S1053811921009939)

[Keil, A., Debener, S., Gratton, G., Junghöfer, M., Kappenman, E. S., Luck, S. J., ... & Yee, C. M. (2014). Committee report: publication guidelines and recommendations for studies using electroencephalography and magnetoencephalography. Psychophysiology, 51(1), 1-21.](https://onlinelibrary.wiley.com/doi/10.1111/psyp.12147)